<?php

namespace CopiaDigital\TailwindSafelist;

/**
 * PHP-based Tailwind CSS generator.
 *
 * Parses Tailwind utility class names (including arbitrary values like
 * `-mt-[20px]`, variants like `md:hover:tw-bg-primary/50`, and the
 * configured class prefix) and emits CSS rules directly. This replaces
 * running `yarn build` on servers that can't run Node.
 *
 * Scope is intentionally pragmatic: it covers the utilities that show
 * up in CMS-authored content (spacing, sizing, layout, flex/grid, color,
 * border, typography, common state variants). Anything not recognised
 * is silently skipped — those classes should already be in the main
 * Tailwind build that ships with the theme.
 */
class CssGenerator
{
    private string $prefix;
    private array $spacing;
    private array $colors;
    private array $fontSizes;
    private array $radii;
    private array $pseudoVariants;
    private array $screenVariants;

    /** Class names to skip — already present in the main bundle. */
    private array $excludeClasses;

    public function __construct(array $config = [])
    {
        $this->prefix = (string) ($config['prefix'] ?? '');
        $this->spacing = $this->normaliseMap($config['spacing'] ?? []);
        $this->colors = $this->normaliseMap($config['colors'] ?? []);
        $this->fontSizes = $this->normaliseMap($config['font_sizes'] ?? []);
        $this->radii = $this->normaliseMap($config['radii'] ?? []);
        $this->excludeClasses = $config['exclude_classes'] ?? [];

        $this->screenVariants = $config['screens'] ?? [
            'sm' => '576px',
            'md' => '768px',
            'lg' => '992px',
            'xl' => '1200px',
            '2xl' => '1400px',
        ];

        $this->pseudoVariants = $config['pseudo_variants'] ?? [
            'hover' => ':hover',
            'focus' => ':focus',
            'focus-within' => ':focus-within',
            'focus-visible' => ':focus-visible',
            'active' => ':active',
            'visited' => ':visited',
            'disabled' => ':disabled',
            'checked' => ':checked',
            'first' => ':first-child',
            'last' => ':last-child',
            'odd' => ':nth-child(odd)',
            'even' => ':nth-child(even)',
            'file' => '::file-selector-button',
            'placeholder' => '::placeholder',
            'before' => '::before',
            'after' => '::after',
        ];
    }

    /**
     * Generate a complete CSS document for a list of class names.
     */
    public function generate(array $classes): string
    {
        $base = '';
        $media = []; // "min-width: 768px" => rules string

        $seen = [];
        foreach ($classes as $class) {
            $class = trim($class);
            if ($class === '' || isset($seen[$class])) {
                continue;
            }
            $seen[$class] = true;

            // Skip classes already present in the compiled bundle.
            if (isset($this->excludeClasses[$class])) {
                continue;
            }

            $rule = $this->compileClass($class);
            if ($rule === null) {
                continue;
            }

            if ($rule['media'] !== null) {
                $media[$rule['media']] = ($media[$rule['media']] ?? '') . $rule['css'];
            } else {
                $base .= $rule['css'];
            }
        }

        $css = "/* Generated by wp-tailwind-safelist. Do not edit. */\n";
        $css .= $base;

        uksort($media, fn($a, $b) => $this->extractPx($a) <=> $this->extractPx($b));
        foreach ($media as $query => $rules) {
            $css .= "@media ($query) {\n$rules}\n";
        }

        return $css;
    }

    private function extractPx(string $query): int
    {
        return (int) preg_replace('/\D+/', '', $query);
    }

    /**
     * Compile a single class name into a CSS rule.
     *
     * @return array{css:string, media:?string}|null
     */
    private function compileClass(string $class): ?array
    {
        ['variants' => $variants, 'utility' => $utility] = $this->splitVariants($class);

        $negative = false;
        if (str_starts_with($utility, '-')) {
            $negative = true;
            $utility = substr($utility, 1);
        }

        if ($this->prefix !== '') {
            if (!str_starts_with($utility, $this->prefix)) {
                return null;
            }
            $utility = substr($utility, strlen($this->prefix));
        }

        $declarations = $this->resolveUtility($utility, $negative);
        if ($declarations === null) {
            return null;
        }

        $pseudo = '';
        $media = null;
        foreach ($variants as $variant) {
            if (isset($this->pseudoVariants[$variant])) {
                $pseudo .= $this->pseudoVariants[$variant];
            } elseif (isset($this->screenVariants[$variant])) {
                $media = 'min-width: ' . $this->screenVariants[$variant];
            } else {
                return null;
            }
        }

        $selector = '.' . $this->escapeSelector($class) . $pseudo;
        return ['css' => "$selector { $declarations }\n", 'media' => $media];
    }

    /**
     * Split a class name into ordered variant chain + final utility.
     * Splits on `:` but ignores `:` inside `[...]`.
     *
     * @return array{variants:array<int,string>, utility:string}
     */
    private function splitVariants(string $class): array
    {
        $parts = [];
        $buf = '';
        $depth = 0;
        $len = strlen($class);
        for ($i = 0; $i < $len; $i++) {
            $c = $class[$i];
            if ($c === '[') $depth++;
            elseif ($c === ']') $depth--;
            if ($c === ':' && $depth === 0) {
                $parts[] = $buf;
                $buf = '';
                continue;
            }
            $buf .= $c;
        }
        $parts[] = $buf;
        $utility = array_pop($parts);
        return ['variants' => $parts, 'utility' => $utility];
    }

    private function escapeSelector(string $class): string
    {
        return preg_replace('/([:\/\[\]\(\)#%.\\\\!,])/', '\\\\$1', $class);
    }

    private function resolveUtility(string $utility, bool $negative): ?string
    {
        if (!$negative) {
            $static = $this->staticUtility($utility);
            if ($static !== null) {
                return $static;
            }
        }
        return $this->parameterisedUtility($utility, $negative);
    }

    private function staticUtility(string $utility): ?string
    {
        static $map = null;
        if ($map === null) {
            $map = [
                // Display
                'block' => 'display: block;',
                'inline-block' => 'display: inline-block;',
                'inline' => 'display: inline;',
                'flex' => 'display: flex;',
                'inline-flex' => 'display: inline-flex;',
                'grid' => 'display: grid;',
                'inline-grid' => 'display: inline-grid;',
                'table' => 'display: table;',
                'table-row' => 'display: table-row;',
                'table-cell' => 'display: table-cell;',
                'contents' => 'display: contents;',
                'hidden' => 'display: none;',
                // Position
                'static' => 'position: static;',
                'fixed' => 'position: fixed;',
                'absolute' => 'position: absolute;',
                'relative' => 'position: relative;',
                'sticky' => 'position: sticky;',
                // Visibility
                'visible' => 'visibility: visible;',
                'invisible' => 'visibility: hidden;',
                // Overflow
                'overflow-auto' => 'overflow: auto;',
                'overflow-hidden' => 'overflow: hidden;',
                'overflow-visible' => 'overflow: visible;',
                'overflow-scroll' => 'overflow: scroll;',
                'overflow-x-auto' => 'overflow-x: auto;',
                'overflow-x-hidden' => 'overflow-x: hidden;',
                'overflow-y-auto' => 'overflow-y: auto;',
                'overflow-y-hidden' => 'overflow-y: hidden;',
                // Flex
                'flex-row' => 'flex-direction: row;',
                'flex-row-reverse' => 'flex-direction: row-reverse;',
                'flex-col' => 'flex-direction: column;',
                'flex-col-reverse' => 'flex-direction: column-reverse;',
                'flex-wrap' => 'flex-wrap: wrap;',
                'flex-nowrap' => 'flex-wrap: nowrap;',
                'flex-wrap-reverse' => 'flex-wrap: wrap-reverse;',
                'flex-1' => 'flex: 1 1 0%;',
                'flex-auto' => 'flex: 1 1 auto;',
                'flex-initial' => 'flex: 0 1 auto;',
                'flex-none' => 'flex: none;',
                'grow' => 'flex-grow: 1;',
                'grow-0' => 'flex-grow: 0;',
                'shrink' => 'flex-shrink: 1;',
                'shrink-0' => 'flex-shrink: 0;',
                // Items / Justify / Self / Content
                'items-start' => 'align-items: flex-start;',
                'items-end' => 'align-items: flex-end;',
                'items-center' => 'align-items: center;',
                'items-baseline' => 'align-items: baseline;',
                'items-stretch' => 'align-items: stretch;',
                'justify-start' => 'justify-content: flex-start;',
                'justify-end' => 'justify-content: flex-end;',
                'justify-center' => 'justify-content: center;',
                'justify-between' => 'justify-content: space-between;',
                'justify-around' => 'justify-content: space-around;',
                'justify-evenly' => 'justify-content: space-evenly;',
                'self-auto' => 'align-self: auto;',
                'self-start' => 'align-self: flex-start;',
                'self-end' => 'align-self: flex-end;',
                'self-center' => 'align-self: center;',
                'self-stretch' => 'align-self: stretch;',
                'content-center' => 'align-content: center;',
                'content-start' => 'align-content: flex-start;',
                'content-end' => 'align-content: flex-end;',
                'content-between' => 'align-content: space-between;',
                'content-around' => 'align-content: space-around;',
                // Text
                'text-left' => 'text-align: left;',
                'text-center' => 'text-align: center;',
                'text-right' => 'text-align: right;',
                'text-justify' => 'text-align: justify;',
                'underline' => 'text-decoration-line: underline;',
                'overline' => 'text-decoration-line: overline;',
                'line-through' => 'text-decoration-line: line-through;',
                'no-underline' => 'text-decoration-line: none;',
                'uppercase' => 'text-transform: uppercase;',
                'lowercase' => 'text-transform: lowercase;',
                'capitalize' => 'text-transform: capitalize;',
                'normal-case' => 'text-transform: none;',
                'italic' => 'font-style: italic;',
                'not-italic' => 'font-style: normal;',
                'truncate' => 'overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
                // Whitespace
                'whitespace-normal' => 'white-space: normal;',
                'whitespace-nowrap' => 'white-space: nowrap;',
                'whitespace-pre' => 'white-space: pre;',
                'whitespace-pre-line' => 'white-space: pre-line;',
                'whitespace-pre-wrap' => 'white-space: pre-wrap;',
                // Font weight
                'font-thin' => 'font-weight: 100;',
                'font-extralight' => 'font-weight: 200;',
                'font-light' => 'font-weight: 300;',
                'font-normal' => 'font-weight: 400;',
                'font-medium' => 'font-weight: 500;',
                'font-semibold' => 'font-weight: 600;',
                'font-bold' => 'font-weight: 700;',
                'font-extrabold' => 'font-weight: 800;',
                'font-black' => 'font-weight: 900;',
                // Cursor
                'cursor-auto' => 'cursor: auto;',
                'cursor-default' => 'cursor: default;',
                'cursor-pointer' => 'cursor: pointer;',
                'cursor-wait' => 'cursor: wait;',
                'cursor-text' => 'cursor: text;',
                'cursor-move' => 'cursor: move;',
                'cursor-not-allowed' => 'cursor: not-allowed;',
                // Misc
                'sr-only' => 'position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border-width: 0;',
                'not-sr-only' => 'position: static; width: auto; height: auto; padding: 0; margin: 0; overflow: visible; clip: auto; white-space: normal;',
                'outline-none' => 'outline: 2px solid transparent; outline-offset: 2px;',
                'border' => 'border-width: 1px;',
                'border-0' => 'border-width: 0;',
                'border-t' => 'border-top-width: 1px;',
                'border-r' => 'border-right-width: 1px;',
                'border-b' => 'border-bottom-width: 1px;',
                'border-l' => 'border-left-width: 1px;',
                'border-x' => 'border-left-width: 1px; border-right-width: 1px;',
                'border-y' => 'border-top-width: 1px; border-bottom-width: 1px;',
                'border-solid' => 'border-style: solid;',
                'border-dashed' => 'border-style: dashed;',
                'border-dotted' => 'border-style: dotted;',
                'border-none' => 'border-style: none;',
                'rounded' => 'border-radius: 0.25rem;',
                'rounded-none' => 'border-radius: 0;',
                'rounded-full' => 'border-radius: 9999px;',
                'shadow' => 'box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);',
                'shadow-none' => 'box-shadow: none;',
                'transition' => 'transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms;',
                'transition-none' => 'transition-property: none;',
                'transition-all' => 'transition-property: all;',
                'transition-colors' => 'transition-property: color, background-color, border-color, fill, stroke;',
                'transition-opacity' => 'transition-property: opacity;',
                'transition-transform' => 'transition-property: transform;',
            ];
        }
        return $map[$utility] ?? null;
    }

    private function parameterisedUtility(string $utility, bool $negative): ?string
    {
        // Margin
        if (preg_match('/^m([trblxy])?-(.+)$/', $utility, $m)) {
            $value = $this->resolveSpacing($m[2], $negative);
            if ($value === null) return null;
            return $this->boxProperty('margin', $m[1] ?? '', $value);
        }
        // Padding (negative invalid)
        if (!$negative && preg_match('/^p([trblxy])?-(.+)$/', $utility, $m)) {
            $value = $this->resolveSpacing($m[2], false);
            if ($value === null) return null;
            return $this->boxProperty('padding', $m[1] ?? '', $value);
        }
        // Inset
        if (preg_match('/^(top|right|bottom|left|inset|inset-x|inset-y)-(.+)$/', $utility, $m)) {
            $value = $this->resolveSpacing($m[2], $negative);
            if ($value === null) return null;
            return $this->insetProperty($m[1], $value);
        }
        // Width / Height / min/max
        if (!$negative && preg_match('/^(w|h|min-w|max-w|min-h|max-h)-(.+)$/', $utility, $m)) {
            $value = $this->resolveSpacing($m[2], false);
            if ($value === null) return null;
            $prop = match ($m[1]) {
                'w' => 'width',
                'h' => 'height',
                'min-w' => 'min-width',
                'max-w' => 'max-width',
                'min-h' => 'min-height',
                'max-h' => 'max-height',
            };
            return "$prop: $value;";
        }
        // size-*
        if (!$negative && preg_match('/^size-(.+)$/', $utility, $m)) {
            $value = $this->resolveSpacing($m[1], false);
            if ($value === null) return null;
            return "width: $value; height: $value;";
        }
        // Gap
        if (!$negative && preg_match('/^gap(-x|-y)?-(.+)$/', $utility, $m)) {
            $value = $this->resolveSpacing($m[2], false);
            if ($value === null) return null;
            return match ($m[1] ?? '') {
                '-x' => "column-gap: $value;",
                '-y' => "row-gap: $value;",
                default => "gap: $value;",
            };
        }
        // Background color
        if (!$negative && preg_match('/^bg-(.+)$/', $utility, $m)) {
            $value = $this->resolveColor($m[1]);
            if ($value === null) return null;
            return "background-color: $value;";
        }
        // Text — size or color
        if (!$negative && preg_match('/^text-(.+)$/', $utility, $m)) {
            $token = $m[1];
            if (isset($this->fontSizes[$token])) {
                return "font-size: {$this->fontSizes[$token]};";
            }
            if (preg_match('/^\[(.+)\]$/', $token, $a)) {
                $v = str_replace('_', ' ', $a[1]);
                if (preg_match('/(px|rem|em|%|vh|vw|ch|ex|pt)$/i', $v)) {
                    return "font-size: $v;";
                }
                return "color: $v;";
            }
            $color = $this->resolveColor($token);
            if ($color !== null) return "color: $color;";
            return null;
        }
        // Numeric font-weight
        if (!$negative && preg_match('/^font-(\d+)$/', $utility, $m)) {
            return "font-weight: {$m[1]};";
        }
        // Leading / tracking
        if (!$negative && preg_match('/^leading-(.+)$/', $utility, $m)) {
            $v = $this->resolveArbitraryOrNumber($m[1]);
            return $v !== null ? "line-height: $v;" : null;
        }
        if (preg_match('/^tracking-(.+)$/', $utility, $m)) {
            $v = $this->resolveArbitraryOrNumber($m[1]);
            if ($v === null) return null;
            return 'letter-spacing: ' . ($negative ? "-$v" : $v) . ';';
        }
        // Border width: border-{n}
        if (!$negative && preg_match('/^border-(\d+)$/', $utility, $m)) {
            return "border-width: {$m[1]}px;";
        }
        if (!$negative && preg_match('/^border-([trbl])-(\d+)$/', $utility, $m)) {
            $side = ['t' => 'top', 'r' => 'right', 'b' => 'bottom', 'l' => 'left'][$m[1]];
            return "border-$side-width: {$m[2]}px;";
        }
        // Border color
        if (!$negative && preg_match('/^border-(.+)$/', $utility, $m)) {
            $color = $this->resolveColor($m[1]);
            if ($color !== null) return "border-color: $color;";
            return null;
        }
        // Rounded with corner + value
        if (!$negative && preg_match('/^rounded-(t|r|b|l|tl|tr|bl|br)-(.+)$/', $utility, $m)) {
            $value = $this->resolveRadius($m[2]);
            if ($value === null) return null;
            return $this->cornerProperty($m[1], $value);
        }
        // Rounded with value only
        if (!$negative && preg_match('/^rounded-(.+)$/', $utility, $m)) {
            // corner-only forms (rounded-t etc.) handled above by static map fallback
            $value = $this->resolveRadius($m[1]);
            if ($value === null) return null;
            return "border-radius: $value;";
        }
        // Opacity
        if (!$negative && preg_match('/^opacity-(\d+)$/', $utility, $m)) {
            return 'opacity: ' . ($m[1] / 100) . ';';
        }
        // Z-index
        if (preg_match('/^z-(.+)$/', $utility, $m)) {
            $v = $this->resolveArbitraryOrNumber($m[1]);
            if ($v === null) return null;
            return 'z-index: ' . ($negative ? "-$v" : $v) . ';';
        }
        // Grid columns / rows
        if (!$negative && preg_match('/^grid-cols-(\d+)$/', $utility, $m)) {
            return "grid-template-columns: repeat({$m[1]}, minmax(0, 1fr));";
        }
        if (!$negative && preg_match('/^grid-cols-\[(.+)\]$/', $utility, $m)) {
            return 'grid-template-columns: ' . str_replace('_', ' ', $m[1]) . ';';
        }
        if (!$negative && preg_match('/^grid-rows-(\d+)$/', $utility, $m)) {
            return "grid-template-rows: repeat({$m[1]}, minmax(0, 1fr));";
        }
        // Span / start / end
        if (!$negative && preg_match('/^col-span-(\d+|full)$/', $utility, $m)) {
            return $m[1] === 'full' ? 'grid-column: 1 / -1;' : "grid-column: span {$m[1]} / span {$m[1]};";
        }
        if (!$negative && preg_match('/^row-span-(\d+|full)$/', $utility, $m)) {
            return $m[1] === 'full' ? 'grid-row: 1 / -1;' : "grid-row: span {$m[1]} / span {$m[1]};";
        }
        if (!$negative && preg_match('/^col-start-(\d+)$/', $utility, $m)) {
            return "grid-column-start: {$m[1]};";
        }
        if (!$negative && preg_match('/^col-end-(\d+)$/', $utility, $m)) {
            return "grid-column-end: {$m[1]};";
        }
        // Order
        if (preg_match('/^order-(\d+)$/', $utility, $m)) {
            return 'order: ' . ($negative ? "-{$m[1]}" : $m[1]) . ';';
        }
        // Aspect
        if (!$negative && preg_match('/^aspect-(.+)$/', $utility, $m)) {
            $map = ['square' => '1 / 1', 'video' => '16 / 9', 'auto' => 'auto'];
            $v = $map[$m[1]] ?? $this->arbitrary($m[1]);
            if ($v === null) return null;
            return "aspect-ratio: $v;";
        }
        // Duration / delay
        if (!$negative && preg_match('/^duration-(\d+)$/', $utility, $m)) {
            return "transition-duration: {$m[1]}ms;";
        }
        if (!$negative && preg_match('/^delay-(\d+)$/', $utility, $m)) {
            return "transition-delay: {$m[1]}ms;";
        }
        // Transforms
        if (preg_match('/^translate-(x|y)-(.+)$/', $utility, $m)) {
            $v = $this->resolveSpacing($m[2], $negative);
            if ($v === null) return null;
            $axis = strtoupper($m[1]);
            return "transform: translate$axis($v);";
        }
        if (preg_match('/^rotate-(.+)$/', $utility, $m)) {
            $v = $this->resolveArbitraryOrNumber($m[1]);
            if ($v === null) return null;
            return 'transform: rotate(' . ($negative ? "-$v" : $v) . 'deg);';
        }
        if (!$negative && preg_match('/^scale-(\d+)$/', $utility, $m)) {
            return 'transform: scale(' . ($m[1] / 100) . ');';
        }

        return null;
    }

    private function boxProperty(string $base, string $side, string $value): string
    {
        return match ($side) {
            '' => "$base: $value;",
            't' => "$base-top: $value;",
            'r' => "$base-right: $value;",
            'b' => "$base-bottom: $value;",
            'l' => "$base-left: $value;",
            'x' => "$base-left: $value; $base-right: $value;",
            'y' => "$base-top: $value; $base-bottom: $value;",
        };
    }

    private function insetProperty(string $key, string $value): string
    {
        return match ($key) {
            'top' => "top: $value;",
            'right' => "right: $value;",
            'bottom' => "bottom: $value;",
            'left' => "left: $value;",
            'inset' => "inset: $value;",
            'inset-x' => "left: $value; right: $value;",
            'inset-y' => "top: $value; bottom: $value;",
        };
    }

    private function cornerProperty(string $corner, string $value): string
    {
        return match ($corner) {
            't' => "border-top-left-radius: $value; border-top-right-radius: $value;",
            'r' => "border-top-right-radius: $value; border-bottom-right-radius: $value;",
            'b' => "border-bottom-left-radius: $value; border-bottom-right-radius: $value;",
            'l' => "border-top-left-radius: $value; border-bottom-left-radius: $value;",
            'tl' => "border-top-left-radius: $value;",
            'tr' => "border-top-right-radius: $value;",
            'bl' => "border-bottom-left-radius: $value;",
            'br' => "border-bottom-right-radius: $value;",
            default => "border-radius: $value;",
        };
    }

    /**
     * Resolve a spacing token: arbitrary, fraction, keyword, theme scale, or default rem.
     */
    private function resolveSpacing(string $token, bool $negative): ?string
    {
        $arb = $this->arbitrary($token);
        if ($arb !== null) {
            return $negative ? $this->negate($arb) : $arb;
        }
        if (preg_match('#^(\d+)/(\d+)$#', $token, $m)) {
            $pct = round(($m[1] / $m[2]) * 100, 6) . '%';
            return $negative ? "-$pct" : $pct;
        }
        $keywords = [
            'auto' => 'auto',
            'full' => '100%',
            'screen' => '100vh',
            'svh' => '100svh',
            'lvh' => '100lvh',
            'dvh' => '100dvh',
            'min' => 'min-content',
            'max' => 'max-content',
            'fit' => 'fit-content',
            'px' => '1px',
            '0' => '0',
        ];
        if (isset($keywords[$token])) {
            $v = $keywords[$token];
            if (in_array($v, ['auto', 'min-content', 'max-content', 'fit-content', '0'], true)) {
                return $v;
            }
            return $negative ? "-$v" : $v;
        }
        if (isset($this->spacing[$token])) {
            $v = $this->spacing[$token];
            return $negative ? "calc($v * -1)" : $v;
        }
        if (is_numeric($token)) {
            $rem = ((float) $token) * 0.25;
            return ($negative ? '-' : '') . $rem . 'rem';
        }
        return null;
    }

    private function resolveColor(string $token): ?string
    {
        $arb = $this->arbitrary($token);
        if ($arb !== null) return $arb;

        if (str_contains($token, '/')) {
            [$name, $alpha] = explode('/', $token, 2);
            $base = $this->colors[$name] ?? null;
            if ($base !== null && is_numeric($alpha)) {
                return "color-mix(in srgb, $base " . (int) $alpha . "%, transparent)";
            }
            return null;
        }

        return $this->colors[$token] ?? null;
    }

    private function resolveRadius(string $token): ?string
    {
        $arb = $this->arbitrary($token);
        if ($arb !== null) return $arb;
        if (isset($this->radii[$token])) return $this->radii[$token];

        $defaults = [
            'none' => '0',
            'sm' => '0.125rem',
            'md' => '0.375rem',
            'lg' => '0.5rem',
            'xl' => '0.75rem',
            '2xl' => '1rem',
            '3xl' => '1.5rem',
            'full' => '9999px',
        ];
        return $defaults[$token] ?? null;
    }

    private function resolveArbitraryOrNumber(string $token): ?string
    {
        $arb = $this->arbitrary($token);
        if ($arb !== null) return $arb;
        if (is_numeric($token)) return $token;
        return null;
    }

    /**
     * Returns the inside of [...] (with `_` → space) or null.
     */
    private function arbitrary(string $token): ?string
    {
        if (preg_match('/^\[(.+)\]$/', $token, $m)) {
            return str_replace('_', ' ', $m[1]);
        }
        return null;
    }

    private function negate(string $value): string
    {
        if ($value === '0' || $value === 'auto') return $value;
        if (preg_match('/^-?[\d.]+([a-z%]+)?$/i', $value)) {
            return str_starts_with($value, '-') ? substr($value, 1) : "-$value";
        }
        return "calc($value * -1)";
    }

    private function normaliseMap(array $map): array
    {
        $out = [];
        foreach ($map as $k => $v) {
            $out[(string) $k] = (string) $v;
        }
        return $out;
    }
}
